apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: perf-node-gather-pods-reader
subjects:
- kind: ServiceAccount
  name: perf-node-gather
  namespace: perf-node-gather
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: perf-node-gather-pods-reader
  apiGroup: rbac.authorization.k8s.io
